[package]
name = "leifs/genrojotree"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
networker = "leifstout/networker@0.3.1"
dataservicetyped = "leifstout/dataservicetyped@1.0.5"
vide = "centau/vide@0.4.0"
vide-ripple = "littensy/vide-ripple@0.10.2"