return {
	Panel_Inventory_Frame = {
		Image = "rbxassetid://139413297842043",
		Size = Vector2.new(1024, 742),
		SliceOffsets = {
			Left = 90,
			Top = 90,
			Right = 90,
			Bottom = 90,
		},
	},

	Panel_Inventory_Slot_Frame = {
		Image = "rbxassetid://119774502274062",
		Size = Vector2.new(155, 200),
		SliceOffsets = {
			Left = 23,
			Top = 30,
			Right = 24,
			Bottom = 30,
		},
	},

	Panel_Inventory_Slot_InnerFrame = {
		Image = "rbxassetid://129072626341496",
		Size = Vector2.new(258, 344),
		SliceOffsets = {
			Left = 23,
			Top = 30,
			Right = 24,
			Bottom = 30,
		},
	},

	Panel_Inventory_Slot_Texture = {
		Image = "rbxassetid://82259814231126",
		Size = Vector2.new(270, 360),
	},
}
