return {
	Panel_Inventory_Frame = {
		Image = "rbxassetid://139413297842043",
		Size = Vector2.new(1024, 742),
		SliceOffsets = {
			Left = 90,
			Top = 90,
			Right = 90,
			Bottom = 90,
		},
	},

	Panel_Inventory_Slot_Frame = {
		Image = "rbxassetid://102237650175922",
		Size = Vector2.new(155, 200),
		SliceOffsets = {
			Left = 23,
			Top = 30,
			Right = 24,
			Bottom = 30,
		},
	},

	Panel_Inventory_Slot_InnerFrame = {
		Image = "rbxassetid://129072626341496",
		Size = Vector2.new(258, 344),
		SliceOffsets = {
			Left = 23,
			Top = 30,
			Right = 24,
			Bottom = 30,
		},
	},

	Panel_Inventory_Slot_Texture = {
		Image = "rbxassetid://82259814231126",
		Size = Vector2.new(270, 360),
	},

	Panel_Inventory_Slot_Selected = {
		Image = "rbxassetid://132107531379998",
		Size = Vector2.new(145, 190),
	},

	Panel_Inventory_Count_Frame = {
		Image = "rbxassetid://131726306840346",
		Size = Vector2.new(244, 75),
	},

	Panel_Inventory_Count_Inside = {
		Image = "rbxassetid://86089989514812",
		Size = Vector2.new(226, 56),
		SliceOffsets = {
			Left = 12,
			Top = 0,
			Right = 12,
			Bottom = 0,
		},
	},

	Example_Icon_Apple = {
		Image = "rbxassetid://118692506564291",
		Size = Vector2.new(160, 160),
	},

	Example_Icon_GoldenApple = {
		Image = "rbxassetid://73344664000729",
		Size = Vector2.new(160, 160),
	},
}
